# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Altera HSSI subsystem device drivers.
#

obj-$(CONFIG_ALTERA_HSSISS) += altera-hssiss.o
altera-hssiss-y := altera_hssiss.o
altera-hssiss-$(CONFIG_DEBUG_FS) += altera_hssiss_debug.o
